services:
  flask-app-chatbot:
    build: ./app
    container_name: flask-app-chatbot
    restart: always
    ports:
      - "5001:5001"  # New port to avoid conflict
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DATABASE_URL: ${DATABASE_URL}
      PORT: ${PORT}
    volumes:
      - ./app:/flask-app/app
      - ./app/templates:/flask-app/app/templates
      - ./uploads:/flask-app/uploads
      - sentence_model_cache:/root/.cache/torch/sentence_transformers
    depends_on:
      - db
volumes:
  sentence_model_cache: