version: '3.8'

services:
  db:
    container_name: ai_chatbot_db
    image: mysql:8.0
    ports:
      - "3307:3306"  # external_port:internal_mysql_port
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: always

volumes:
  mysql-data:
